"""Initial migration

Revision ID: a58038e90bc9
Revises: 
Create Date: 2023-12-14 01:45:06.218856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a58038e90bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_song')
    op.drop_table('Playlist')
    op.drop_table('follow_artist')
    op.drop_table('Friend')
    op.drop_table('listen_now')
    op.drop_table('Artist')
    op.drop_table('follow_album')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index('artist')

    op.drop_table('album')
    op.drop_table('Song')
    op.drop_table('owned')
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('uname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['uname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('uname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    op.create_table('owned',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.ID'], name='owned_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Song',
    sa.Column('ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('artist_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('album_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('release', mysql.DATETIME(), nullable=True),
    sa.Column('genre', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('listens', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filepath', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.ID'], name='song_ibfk_2'),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.ID'], name='song_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('album',
    sa.Column('ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('artist_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('release_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.ID'], name='album_ibfk_1'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.create_index('artist', ['artist_id'], unique=False)

    op.create_table('follow_album',
    sa.Column('album', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album'], ['album.ID'], name='follow_album_ibfk_1'),
    sa.ForeignKeyConstraint(['user'], ['User.ID'], name='follow_album_ibfk_2'),
    sa.PrimaryKeyConstraint('album', 'user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Artist',
    sa.Column('ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('followerCount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dateJoin', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('listen_now',
    sa.Column('userID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('songID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.ID'], name='listen_now_ibfk_1'),
    sa.PrimaryKeyConstraint('userID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Friend',
    sa.Column('u1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('u2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['u1'], ['User.ID'], name='friend_ibfk_1'),
    sa.ForeignKeyConstraint(['u2'], ['User.ID'], name='friend_ibfk_2'),
    sa.PrimaryKeyConstraint('u1', 'u2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('follow_artist',
    sa.Column('artist', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['Artist.ID'], name='follow_artist_ibfk_1'),
    sa.ForeignKeyConstraint(['user'], ['User.ID'], name='follow_artist_ibfk_2'),
    sa.PrimaryKeyConstraint('artist', 'user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Playlist',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('playlist_song',
    sa.Column('playlist_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['Playlist.ID'], name='playlist_song_ibfk_1'),
    sa.ForeignKeyConstraint(['song_id'], ['Song.ID'], name='fk_playlist_song_song_id'),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
